version: '3'

services:
  traefik:
    image: traefik:v2.1
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/letsencrypt:/letsencrypt
      - ./config/traefik:/etc/traefik
      - ./log/traefik:/var/log
    container_name: traefik