version: '3'

services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    volumes:
      - ./volumes/mongo:/data/db
  traefik:
    image: traefik:v2.1
    container_name: traefik
    labels:
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.hxtao.xyz`)"
      - "traefik.http.routers.traefik.tls.certResolver=mytlschallenge"
      - "traefik.http.routers.traefik.middlewares=auth@file"
      - "traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http_catchall.entrypoints=web"
      - "traefik.http.routers.http_catchall.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/letsencrypt:/letsencrypt
      - ./config/traefik:/etc/traefik
      - ./log/traefik:/var/log
  # note.hxtao.xyz
  note:
    image: hxtao1996/note.hxtao:0.0.1
    container_name: note
    labels:
      - "traefik.http.routers.note.rule=Host(`note.hxtao.xyz`)"
      - "traefik.http.routers.note.middlewares=security-headers@file"
      - "traefik.http.routers.note.tls.certResolver=mytlschallenge"
  # note-manage.hxtao.xyz
  note-manage:
    image: hxtao1996/note-manage.hxtao:0.0.1
    container_name: note-manage
    labels:
      - "traefik.http.routers.note-manage.rule=Host(`note-manage.hxtao.xyz`)"
      - "traefik.http.routers.note-manage.middlewares=security-headers@file"
      - "traefik.http.routers.note-manage.tls.certResolver=mytlschallenge"
  # note-api.hxtao.xyz
  note-api:
    image: hxtao1996/note-api:0.0.1
    container_name: note-api
    volumes:
      - ./config/note-api/config.yml:/app/config.yml
      - ./log/note-api:/root/.pm2
      - ./volumes/note-api/public:/app/public
      - ./volumes/note-api/.backup:/app/.backup
    depends_on:
      - mongo
    labels:
      - "traefik.http.routers.note-api.rule=Host(`note-api.hxtao.xyz`)"
      - "traefik.http.routers.note-api.middlewares=security-headers@file"
      - "traefik.http.routers.note-api.tls.certResolver=mytlschallenge"