http:
  # routers:
    
  middlewares:
    redirect:
      redirectScheme:
        scheme: https
    auth:
      basicAuth:
        users:
          - "user:$$apr1$$09zdWgXw$$U3zdCZhsFFS6UY/KmNGh//"  # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
    security-headers:
      headers:
        # strict-transport-security: "max-age=31536000; includeSubDomains; preload"
        #    doc:
        #      - https://developer.mozilla.org/zh-CN/docs/Security/HTTP_Strict_Transport_Security  告诉浏览器只能通过 https 访问
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true # Set forceSTSHeader to true, to add the STS header even when the connection is HTTP. doc: https://docs.traefik.io/middlewares/headers/#forcestsheader


        # content-security-policy
        #   doc:
        #     - https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CSP  内容安全策略 
        #     - https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy
        contentSecurityPolicy: "default-src 'self' *.hxtao.xyz *.googletagmanager.com *.googleapis.com *.gstatic.com at.alicdn.com music.163.com www.youtube.com player.bilibili.com data: blob: ; style-src 'self' 'unsafe-inline' *.hxtao.xyz *.googleapis.com at.alicdn.com music.163.com www.youtube.com player.bilibili.com data: blob: ;"

        # x-content-type-options: nosniff
        #   doc:
        #     - https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/X-Content-Type-Options  禁止浏览器嗅探行为
        contentTypeNosniff: true

        # X-XSS-Protection: 1; mode=block  开启 xss 过滤，遇到攻击时阻止页面加载
        #   doc:
        #     - https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/X-XSS-Protection
        browserXssFilter: true

        # x-frame-options: sameorigin
        #   doc:
        #     - https://developer.mozilla.org/zh-CN/docs/Web/HTTP/X-Frame-Options
        frameDeny: true
        customFrameOptionsValue: "sameorigin" # 页面就可以在同域名页面的 frame 中嵌套 The customFrameOptionsValue allows the X-Frame-Options header value to be set with a custom value. This overrides the FrameDeny option. doc: https://docs.traefik.io/middlewares/headers/#framedeny

        # referrer-policy: same-origin
        #   doc:
        #     - https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Referrer-Policy
        referrerPolicy: "same-origin"  # 只对同源地址发送引用地址信息

        # feature-policy: ibrate 'self'
        #   doc:
        #     - https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Feature-Policy  处于实验中
        #     - https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Feature-Policy/vibrate 是否可以调用振动 API
        featurePolicy: "vibrate 'self'"  # 只允许自己（当前页面）的调用振动 API

tls:
  options:
    default:
      minVersion: VersionTLS12

