http:
  routers:
    api-tls:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik.hxtao.xyz`)"
      service: api@internal
      tls:
        certResolver: "mytlschallenge"
      middlewares:
        - "auth"
        - "security-headers"
    api:
      entryPoints:
        - "web"
      rule: "Host(`traefik.hxtao.xyz`)"
      service: api@internal
      middlewares:
        - "redirect"

  middlewares:
    redirect:
      redirectScheme:
        scheme: https
    auth:
      basicAuth:
        users:
          - "traefik@hxtao:$apr1$QQgT/Het$N2oU.YVRomTdup8vHr.Mm1"  # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline'"
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "same-origin"
        featurePolicy: "vibrate 'self'"
        stsSeconds: 315360000

tls:
  options:
    default:
      minVersion: VersionTLS12

